### ISSUE TITLE
Packages are not visible in the pipit search result properly

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#446] opened 2016-04-28 13:36 UTC
Originally reported by: **Luca Rebuffi (Bitbucket: [lucarebuffi](https://bitbucket.org/lucarebuffi), GitHub: [lucarebuffi](https://github.com/lucarebuffi))**

----------------------------------------

All of my packages with the keyword "oasys" are still visibile with a search (only a huge list of deleted old versions are visible). Even if I do a direct search with the package name the result is inconsistent. Please fix it, this is a SEVERE problem, compromising the usability of my pip-based self-upgrading application!

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/446

**Comment by kernc** [comment] 2016-06-18 15:16
Duplicate of https://github.com/pypa/pypi-legacy/issues/397

**Closed** 2016-06-18 15:17 UTC
Labels: bug, duplicate, major
