### ISSUE TITLE
Download of Flask still doesn't work form AWS

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#366] opened 2015-12-24 20:07 UTC
Originally reported by: **Chuck Karish (Bitbucket: [chuck_karish](https://bitbucket.org/chuck_karish), GitHub: Unknown)**

----------------------------------------

Follow-on for issue #365:

The index for Flask now shows up for me both on my laptop and from a CI host in the AWS Oregon data center. The download works on my laptop but not on the CI host.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/366

**Comment by berkerpeksag** [comment] 2016-06-19 18:54
This is basically a duplicate of #365. I was able to download flask 0.10.1 from a machine hosted in AWS (probably from a different data center though.)

**Closed by berkerpeksag** 2016-06-19 18:54 UTC
