### ISSUE TITLE
pypi.python.org exposes internal IP addresses

### ISSUE THREAD

**Issue by bschumacher** [pypa/pypi-legacy#640] opened 2017-05-06 18:09 UTC
Before opening an issue for PyPI, please note the following:
  - This is for the codebase currently running pypi.python.org
  - [Warehouse](https://github.com/pypa/warehouse) is soon to replace this codebase. Some issues may be deferred to the issue tracker for [Warehouse](https://github.com/pypa/warehouse/issues) rather than be addressed here.
  - We do not maintain individual packages installed from PyPI, please seek out the maintainer

I recently updated a package the IP address that it shows in the Journal is 10.81.172.78, which does not correspond to any of my network addresses thus it can be assumed that it is an internal address on pypi.python.org's end.

Didn't see any existing issues, this might not even be the correct place to report the issue but figured I would alert someone.

**Comment by AraHaan** [comment] 2017-05-06 22:49
Interesting. *What could possibly go wrong with exposing the internal PyPi IP address?* A lot if the right person sees it and attempts to DDoS it.

**Comment by jamadden** [comment] 2017-06-02 15:54
Thanks for the report! I believe this is a duplicate of #603. If you can help with reproducing it or providing details, please respond on that issue.

**Closed by jamadden** 2017-06-02 15:54 UTC
Labels: duplicate
