### ISSUE TITLE
PyPI database not updated?

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#459] opened 2016-06-02 17:05 UTC
Originally reported by: **Skip Montanaro (Bitbucket: [skip_montanaro](https://bitbucket.org/skip_montanaro), GitHub: Unknown)**

----------------------------------------

When I searched PyPI for "sip", among other things, I saw "SIP 4.17" and "SIP 4.16.9". Clicking either link results in a 404 error. Stripping off the specific version and visiting https://pypi.python.org/pypi/SIP/ explains why. Back in April, SIP 4.18 was apparently released, and that's the only specific version visible to end users. Shouldn't whatever database which references the now defunct 4.16.9 and 4.17 versions have been updated by now (early June) and been replaced by 4.18?

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/459

**Comment by kernc** [comment] 2016-06-18 15:15
Duplicate of https://github.com/pypa/pypi-legacy/issues/397

**Closed** 2016-06-18 15:18 UTC
Labels: bug, duplicate, major
