### ISSUE TITLE
package "petrophysics" not in search results

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#468] opened 2016-06-16 15:35 UTC
Originally reported by: **petrophysics (Bitbucket: [bit000user](https://bitbucket.org/bit000user), GitHub: Unknown)**

----------------------------------------

I can install the package https://pypi.python.org/pypi/petrophysics/ with "pip install petrophysics", but when I search for it I have got: "There were no matches." Please help with this issue.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/468

**Comment by kernc** [comment] 2016-06-18 15:16
Duplicate of https://github.com/pypa/pypi-legacy/issues/397

**Closed** 2016-06-18 15:18 UTC
Labels: bug, duplicate, major
