### ISSUE TITLE
pythonhosted.org doc upload form is gone and "destroy doc" button doesn't work

### ISSUE THREAD

**Issue by giampaolo** [pypa/pypi-legacy#700] opened 2017-09-05 02:51 UTC
http://pythonhosted.org/ says:
> To upload documentation, go to your package edit page (http://pypi.python.org/pypi?%3Aaction=pkg_edit&name=yourpackage), and fill out the form at the bottom of the page
...but the form is gone and it's no longer possible to upload doc.

The only available option in terms of actions allowed by the web page is the "destroy documentation" button which unfortunately doesn't work.

This is currently severely affecting my psutil project as I released a new major version but I can't upload the new doc nor move it somewhere else and destroy the old one.

**Comment by loli** [comment] 2017-09-20 17:14
Encountered the same problem.

Releasing a new package version, I though I had to delete the old documentation before being able to upload a new one. But now there's neither the upload form nor `python setup.py upload_docs` working.

Any way to upload to pythonhosted.org? I have links in so many places pointing towards that place!

**Comment by phdru** [comment] 2017-09-22 09:35
I'm also interested in destroying my outdated docs.

**Comment by urinieto** [comment] 2017-10-01 22:39
Has this been addressed yet? Can't find the upload button either.

**Comment by pvcraven** [comment] 2017-11-13 22:33
I also couldn't find the upload button. I was able to destroy the documentation, although it returned and error because it timed-out.

**Comment by pvcraven** [comment] 2017-11-13 22:34
Oh, this looks like a duplicate of https://github.com/pypa/pypi-legacy/issues/672

**Comment by di** [comment] 2018-04-04 03:40
Uploading documentation is no longer supported, please use a service like https://readthedocs.org/ instead.

Destroying documentation is now possible via the interface at https://pypi.org:

* Log in
* Navigate to https://pypi.org/manage/projects/
* Select the project you'd like to remove documentation for
* Select "Documentation" on the left-hand navigation
* You will be presented with a button to destroy the documentation:

![](https://user-images.githubusercontent.com/1200832/37878355-f4952fec-3035-11e8-9335-b80889a75254.png)

**Closed by di** 2018-04-04 03:40 UTC
