### ISSUE TITLE
Package description formatting seems broken for several packages

### ISSUE THREAD

**Issue by malemburg** [pypa/pypi-legacy#558] opened 2016-11-22 10:18 UTC
Several packages on PyPI which have ReST formatted descriptions are no longer shown with rendered output, but instead show the raw ReST text which is hard to read and not very user friendly to use (e.g. links don't work).

Examples:
 * https://pypi.python.org/pypi/kafka_influxdb
 * https://pypi.python.org/pypi/simpleflow

Other packages show the ReST descriptions fine, so perhaps this is the same issue as #214, where even small errors cause the description not to get rendered at all as opposed to showing the inline error message which docutils normally output.

**Comment by dstufft** [comment] 2016-11-22 15:52
This generally means that there is an error in their description somewhere. If you download them you can do ``pip install readme-renderer`` and then do ``python setup.py check -r -s`` to see what the actual error is.

**Comment by jamadden** [comment] 2017-06-02 15:40
As this appears to be a duplicate of #214, and as warehouse (the replacement for PyPI) will be using [readme_renderer](https://github.com/pypa/readme_renderer) to render documents, and as both of the packages specifically referenced in the report have corrected their documents, I believe we can close this issue.

**Closed by jamadden** 2017-06-02 15:40 UTC
Labels: duplicate
