### ISSUE TITLE
Missing trove classifier for Apache License, Version 2.0

### ISSUE THREAD

**Issue by ndparker** [pypa/pypi-legacy#564] opened 2016-11-30 21:14 UTC
Hi,

I'm proposing to add `License :: OSI Approved :: Apache License, Version 2.0` as a classifier.
Note that this completely differs from the "License :: OSI Approved :: Apache Software License".

Thanks.

**Comment by berkerpeksag** [comment] 2016-11-30 22:14
Thanks for the report! This looks like a duplicate of #91.

**Closed by berkerpeksag** 2016-11-30 22:14 UTC
