### ISSUE TITLE
Error after I upload documentation

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#454] opened 2016-05-23 22:41 UTC
Originally reported by: **Thomas Levine (Bitbucket: [tlevine](https://bitbucket.org/tlevine), GitHub: [tlevine](https://github.com/tlevine))**

----------------------------------------

After I uploaded documentation, I got this message.

> # Error 503 backend read error
>
> backend read error
> ### Guru Mediation:
> Details: cache-ord1720-ORD 1463871649 2300673216
> *****
> Varnish cache server

The documentation showed up on pythonhosted.org as I expected, so I think this is just an error in displaying the webpage. 

The URL is "https://pypi.python.org/pypi", and new request to this URL works just fine.

I recall getting a similar error another time that I uploaded documentation, maybe a few months ago.

I have uploaded documentation without this error before, and I recall getting a very bland message indicating that it worked, not a link to the list of packages.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/454

**Comment by berkerpeksag** [comment] 2016-06-21 03:11
This is a duplicate of #266.

**Closed by berkerpeksag** 2016-06-21 03:11 UTC
