### ISSUE TITLE
version of pip package no longer accessible via pip

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#444] opened 2016-04-27 19:28 UTC
Originally reported by: **ambert ho (Bitbucket: [ambertch](https://bitbucket.org/ambertch), GitHub: [ambertch](https://github.com/ambertch))**

----------------------------------------

Pubnub 3.3.2 no longer can be installed via pip, "pip install pubnub==3.3.2 --allow-external=pubnub --allow-unverified=pubnub" no longer works

I see that pubnub 3.3.1 has a download link and works through pip, but 3.3.2 does not have a download link

Thanks!
Ambert

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/444

**Comment by kernc** [comment] 2016-06-18 15:16
Duplicate of https://github.com/pypa/pypi-legacy/issues/397

**Closed** 2016-06-18 15:16 UTC
Labels: bug, duplicate, major
