### ISSUE TITLE
Request ownership change for netapp.santricty packages

### ISSUE THREAD

**Issue by gmarks-ntap** [pypa/pypi-legacy#710] opened 2017-10-06 17:42 UTC
I'm trying to publish an update for the netapp.santricity packages on pypi and it's not working because my account doesn't have permissions for that project.  The original publisher is no longer with the company and we do not have the credentials for the original account.  Any help in changing ownership permissions for this project would be appreciated.

**Comment by ewdurbin** [comment] 2017-10-11 22:15
@gmarks-ntap I've confirmed that the previous user was registered with a netapp.com email address. there are a number of users currently registered with PyPI who also have a confirmed netapp.com address. I've emailed the current owner and if we don't hear from them in 2-3 days or get a bounce we can move it to one of those other users.

**Comment by ewdurbin** [comment] 2017-10-19 14:17
@gmarks-ntap confirmation looks good, is there a specific PyPI user that is registered with a @netapp.com email address that you'd like this transferred to?

**Comment by gmarks-ntap** [comment] 2017-10-20 16:00
Yes, let's use my account please.  It is the same username that I'm using here on github, "gmarks-ntap".  Thanks for working on this!

**Comment by brainwane** [comment] 2020-05-30 01:32
I'm sorry for the wait. I'm not clear whether this request was resolved; I'm responding in case it was not.

We have archived this repository since it's about the legacy PyPI codebase. There's a new support ticket queue and I ask that, if you are still interested in this request, you [re-open your issue there](https://github.com/pypa/pypi-support/issues/new?labels=PEP+541&template=pep541-request.md&title=PEP+541+Request%3A+PROJECT_NAME) so we can follow up.

We're working on implementing PEP 541 with a new process -- you can subscribe to https://github.com/pypa/warehouse/issues/1506 to follow our progress. Once we do that, we'll start working through all the requests for package transfers within https://github.com/pypa/pypi-support/ .

Until then, unfortunately, all I can advise you to do is wait. My apologies.

**Closed by brainwane** 2020-05-30 01:32 UTC
Labels: PEP 541
