### ISSUE TITLE
my package not in search results

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#463] opened 2016-06-10 17:47 UTC
Originally reported by: **Eric Shaw (Bitbucket: [eric-s-s](https://bitbucket.org/eric-s-s), GitHub: [eric-s-s](https://github.com/eric-s-s))**

----------------------------------------

i know it's not new.  my package has been on pypi for over a month.  it doesn't show up in searches using the package name or key words.  i can install using pip and google search will find it.  is there any recent news on when/whether this issue will be resolved?

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/463

**Comment by kernc** [comment] 2016-06-18 15:15
Duplicate of https://github.com/pypa/pypi-legacy/issues/397

**Closed** 2016-06-18 15:19 UTC
Labels: bug, duplicate, major

**Comment by lucarebuffi** [comment] 2016-06-18 16:04
They are not going to fix it. This bug is signalled since several months, with several request/issues/etc..., but I read that developers decided that, since they are moving to a new platform (Pypi Warehouse) and since the bug does not affect the pip install command, nothing will be done. I arranged by searching the packages with my user name in pypi, and it works. Regards, Luca Rebuffi.

**Comment by eric-s-s** [comment] 2016-06-20 18:39
thank you for the update.
