### ISSUE TITLE
blowing away old documentation on http://pythonhosted.org/{package-name}/

### ISSUE THREAD

**Issue by cjw296** [pypa/pypi-legacy#765] opened 2018-01-26 09:42 UTC
I used to upload my docs to http://pythonhosted.org/{package-name}/.

Now I use readthedocs, but what's the best way to blow away old documentation, such as, for example:

http://pythonhosted.org/mailinglogger/

**Comment by ewdurbin** [comment] 2018-01-26 13:36
In your project management page, there is a `Destroy Documentation` button. Does this not work for you?

https://pypi.python.org/pypi?%3Aaction=pkg_edit&name=malinglogger

**Comment by berkerpeksag** [comment] 2018-01-26 13:40
By the way, there are some user reports saying that the "Destroy Documentation" button doesn't work: #700

**Comment by ewdurbin** [comment] 2018-01-26 13:41
Thanks @berkerpeksag, will look into this today.

**Comment by ewdurbin** [comment] 2018-01-26 13:41
@cjw296 assuming that button does not work for you, closing as dupe of #700

**Closed by ewdurbin** 2018-01-26 13:41 UTC

**Comment by cjw296** [comment] 2018-01-26 13:56
It did work for me, just very hard to find a link to 'edit' my package, got it now...
