### ISSUE TITLE
API-s don't return "requires_dist" for most packages

### ISSUE THREAD

**Issue by aivarannamaa** [pypa/pypi-legacy#622] opened 2017-03-28 08:41 UTC
I'm writing a simple pip GUI, which is supposed to show information about packages available at PyPI. Among this information I would like to list the required packages.

While browsing API result of one of my own packages (https://pypi.python.org/pypi/thonny/2.0.7/json) I got the impression that requirements are given under key `"dist_requires"`.

To my surprise, most packages I tried (and which do have dependencies), don't have this key in their API result. Examples:

- https://pypi.python.org/pypi/matplotlib/2.0.0/json
- https://pypi.python.org/pypi/pandas/0.19.2/json
- https://pypi.python.org/pypi/Sphinx/1.5.3/json

Same thing with XML-RPC

I inspected setup.py of Sphinx (https://github.com/sphinx-doc/sphinx/blob/master/setup.py) and it uses setuptools and `install_requires`, just like Thonny (https://bitbucket.org/plas/thonny/src/b9e4c19f02367341827777780834e9eefbdd2265/setup.py?at=master&fileviewer=file-view-default).

I can't see why is `requires_dist` missing from Sphinx's API output.

**Comment by aivarannamaa** [comment] 2017-03-28 08:49
I now noticed that XML-RPC with `ServerProxy('https://pypi.org/pypi')` does give `dist_requires` for Sphinx but it's empty list.

**Comment by jamadden** [comment] 2017-06-02 15:51
I suspect you'll find that the difference is whether the project uploads binary wheels (and whether they upload the binary wheel *first* if they upload wheels and sdists). PyPI appears to only extract this extra metadata from a wheel, and only if a wheel is the first artifact uploaded for a release (I haven't checked the code for that, but that's my experience). This is part of the reason why tools like [twine upload wheels first](https://github.com/pypa/twine/issues/106).

**Comment by di** [comment] 2018-04-04 03:59
Regarding the missing field, I'd recommend pointing your pip GUI at `pypi.org` instead, where the `requires_dist` field will always be present even if empty ([see our migration guide here](https://warehouse.readthedocs.io/api-reference/integration-guide/#migrating-to-the-new-pypi)).

Regarding _why_ the `requires_dist` field is sometimes empty, I'm closing as this is expected behavior. For more background on why, see https://di.codes/articles/2018/03/05/why-pypi-doesnt-know-dependencies

**Closed by di** 2018-04-04 03:59 UTC
