### ISSUE TITLE
https://pypi.python.org/simple serving malformed HTML?

### ISSUE THREAD

**Issue by boegel** [pypa/pypi-legacy#783] opened 2018-03-16 15:52 UTC
For some reason unclear to me, we suddenly started getting parse errors for the HTML pages serves by `https://pypi.python.org/simple`.

Example (this worked fine a couple of hours ago):

```
$ curl -L https://pypi.python.org/simple/easybuild > easybuild.html
$ python -c "from xml.etree import ElementTree; ElementTree.parse('easybuild.html')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: mismatched tag: line 65, column 6
```

Any ideas what may be causing this? Have there be any changes to what `https://pypi.python.org/simple` serves in the last couple of hours?

I'm including the contents of the served HTML file as well. I can't seem to spot what exactly is wrong here though... Line 65 is the `    </body>` line.

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Links for easybuild</title>
  </head>
  <body>
    <h1>Links for easybuild</h1>
    <a href="https://files.pythonhosted.org/packages/40/33/fe5214954b73338290b01ca6e6c211e29eacd30b0c660bc0da233fcc7047/easybuild-1.0.0.tar.gz#sha256=7aa5c7f8330690638849519fe68c05c6020bddd8ddc12d02fd10e1cf3dc7c6b3">easybuild-1.0.0.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/33/76/597fb41ff7c76226c0fb2c839976a717c6f6778ada906c8fdb2442473c7f/easybuild-1.0.1.tar.gz#sha256=7e3182e0bb85a7c10934b6212834546d5956d400b8298e0565ae6a68b57ea57f">easybuild-1.0.1.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/00/40/850c39cd00c338c041d899c09f438ced4981d8ab4bfa7cc0fef2ad89f16f/easybuild-1.0.2.tar.gz#sha256=9d26501c61b16568760293111c5160f6a589a13ca372c798e433b2d0480da3e5">easybuild-1.0.2.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/76/30/9a445d19f7f71fe83a0c1f7a70b4d776ef9021176edb7213dc00538d4489/easybuild-1.1.0.tar.gz#sha256=6eeda65e182d6def655435ca29a73a093a6e83852564673f336f209ee039c4b7">easybuild-1.1.0.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/c7/50/11488161089087f9260814a457532b6a742add62a7fb1a1b3b22fa0329d0/easybuild-1.2.0rc1.tar.gz#sha256=6f9c15a868d1106ef6744af0530cbba38bf8a310d6521386efe15aeaa431666c">easybuild-1.2.0rc1.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/cf/2d/74c10e939a019726c1d59b138ccace41129069adfa211265acc84e28e361/easybuild-1.2.0.tar.gz#sha256=4d126d03a26ea2d7d720a72884d28102dec3308d7ac28a59aeb255af395c2d3e">easybuild-1.2.0.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/c7/47/4cdee14c75793171a010dac6f2b4327cb038ba6ea016c0438e4c9a25c96e/easybuild-1.3.0.tar.gz#sha256=acd49550f5c258cc5127cfa8c153f4c3736657dec684d5ff51dbd2ef167de682">easybuild-1.3.0.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/7f/e1/d26a87284b0237950268ce570cf4c8d5f8bc0dffbc8802bc0b1a884a8034/easybuild-1.4.0.tar.gz#sha256=3f3e2ec9430429f3676e12452c72b941068670012e3534b2496a5e57af3826ec">easybuild-1.4.0.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/22/ef/940a39c883ac156c5f9382992bc08650c585ea2164f5871949e250c4cabf/easybuild-1.5.0.tar.gz#sha256=ade81960b1df664cb2725242587437f98a52b272b57c5c1084090f868323292c">easybuild-1.5.0.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/2e/2a/b8bd5195d8453e8befc98a320e045a56633466d1e566ad2598660b0f5269/easybuild-1.6.0.tar.gz#sha256=3db6b70f0544b3c4c9bf6d5b3c68c50ba3c2eaa6426ca3e1560399c9ab1e867c">easybuild-1.6.0.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/36/7e/1387e70235eb8640c66caffb04a716ecc686cd8ea7625173b759a86001f2/easybuild-1.7.0.tar.gz#sha256=180aa6cdbc08c8de563789f856d471bcf8a51118c59e1294235a0f5a9d2c1c96">easybuild-1.7.0.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/de/3e/c52a2c15c05bf09f2cf04b23dc7328eb05c84992c3f7e82ab4667fad710b/easybuild-1.8.0.tar.gz#sha256=0ffdb6e626de02699e194b95318d60ecdc80bf6bf0643464ec2b2f9f8cf57cd1">easybuild-1.8.0.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/a7/ed/ad79d72449cb93ef3e0b5b77471ce2da2156a2235a24bb66daa44c2f9b17/easybuild-1.8.1.tar.gz#sha256=c1a3825ed688ede93d5f0b5175d14177a3cb73ad42f2122767b76e1aa38a1c95">easybuild-1.8.1.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/fd/27/f5507c5357a667844d2766c856a00628253a29349e9685553028f4739eda/easybuild-1.8.2.tar.gz#sha256=e35b5364526d48f6ae7af0eb5c23f2e6920f7988f4f388f07993c0af35bf017c">easybuild-1.8.2.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/7f/5a/7eb047124982116bc7198dfa0518a623b7c7610214e69f9c2ddea04e6947/easybuild-1.9.0.tar.gz#sha256=e1e48424ffd1266222cc376a3095a5e4defabd7919ba8a9f4cbaf2d6097596b5">easybuild-1.9.0.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/11/b1/19d37d43824f52c6bd7ec80de1dec38a3ce1851e8247b69e250705881523/easybuild-1.10.0.tar.gz#sha256=cc0e3565daad7f5e8e95c07553bf765a249c2edf6d1d701c2450d5a235a80f37">easybuild-1.10.0.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/1f/97/9a4a887f3e63a98e708c6a06fc57edd47f4a554ec98c189d2e344a1ad105/easybuild-1.11.0.tar.gz#sha256=81b006d4625576ebf45f89aef571519fcd274fa19589e163e93b90e25d7e0c97">easybuild-1.11.0.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/9d/3a/fc33f532e76d963f7cfa82f608e8abee2dd9d2152625bc3656f3721745e4/easybuild-1.11.1.tar.gz#sha256=081bf6d2ee8375c0e439aec896ebca754985c096162be64b1613e9be3c6f2743">easybuild-1.11.1.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/30/01/394553eb3f2a542a1aed932df7953d6d208629cd5df7ad57add91c3d4113/easybuild-1.12.0.tar.gz#sha256=72c6185d0b64b83845ac67817d0dcf7d3e93d2bb24af127597e4b64b0766a131">easybuild-1.12.0.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/01/3a/c514039c7224b69ad5b61d334af3fc1db774be149b6789be8d681cb3d3ed/easybuild-1.12.1.tar.gz#sha256=b0e49526fd7ee26c59d932fb88003c1bf9bc3af4a237c70f7ff5bcc0c1e7f175">easybuild-1.12.1.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/c0/1f/2b93bc3d6d0d57761b39118f6a31ddf517e2f0786b7666d05f380da7926a/easybuild-1.13.0.tar.gz#sha256=5f7a31cbfdbc8c247cc35dedbbaa4d0a0b32d41aa9f787f8b7fb60050d567c50">easybuild-1.13.0.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/7f/72/1909c7c391a5a14162970b5d640e76293a4438a7007853bf5ab980019a26/easybuild-1.14.0.tar.gz#sha256=53331f233be80e70a471c694fcbe39c13619f2b0c0728816fd017c6c164095b8">easybuild-1.14.0.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/dd/5c/c7fcaa5481620d17caadb9b10dec437a1ed81324524a8dcff7c77545b490/easybuild-1.15.0.tar.gz#sha256=fd945a80832a2f854287220155ef9918031b78319ab412c6ae4a06d2533ffa6e">easybuild-1.15.0.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/f4/09/94692b29fedee73e33e96dc6049cf5e3b0b0ca6a729799ebac743d348ae0/easybuild-1.15.1.tar.gz#sha256=1b32541250726beb74574dcf4159f0da28febdc4e65e7b44b9620064a2c78e86">easybuild-1.15.1.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/a2/9e/037df822d74efae573be0928c1e273697a48fadca2cf6ac2aa29ab89c53b/easybuild-1.15.2.tar.gz#sha256=e9795db527ace6c6213b98827c47fe9b3ab053e99e81f1fd9f8c8cbdeb0925cb">easybuild-1.15.2.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/a4/bf/1e20bb8eea8ba51059efd446b7632539053b0fb10f40c5f9ec8a13f4d4aa/easybuild-1.16.0.tar.gz#sha256=d174ecaefda2f2bb34a8b625a085f2da11c4a5a463664a45fec931b4d5a17229">easybuild-1.16.0.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/8f/8d/73187f1d969d927fb145ba6ba87df431bede0f042451f7dbdf27253136be/easybuild-1.16.1.tar.gz#sha256=e37d2369a475aa60ec9d83ca2633f18943b912bea2bd0ebb948f39c204d7680d">easybuild-1.16.1.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/1f/b2/50331811070ed3ebc8888ddc7966efb0f92f4ca5c91b9d0875ab51792757/easybuild-1.16.2.tar.gz#sha256=cae6dd98e6b88cc8a77397fd52c5eb7c8af89da1ca53cd467cde183767e88573">easybuild-1.16.2.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/b1/80/34e9ce056a60d01a19ac5160bd59a36aac0d20d987b5957543228291b6e3/easybuild-2.0.0.tar.gz#sha256=ce42fd03c615b2cb13046ea794dfc4b3936d9a1a3ceb2c54b0f0ea43c44a5531">easybuild-2.0.0.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/a0/70/d65770e5b4f2bb8743761c01925e58fc7455d96a12802b886ec1aa492e80/easybuild-2.1.0.tar.gz#sha256=4a276ffb31acfb135a8b41ab97f3fecdc1209edba3f6ee512132bc9d31b1ff66">easybuild-2.1.0.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/ad/84/3800fc4775e07262cde10f48e5592379ccd8fa48b4e635485533378f2bcf/easybuild-2.1.1.tar.gz#sha256=9aee8f8e6494c251486a5028e92b382d9495ad9069286f4f3e6e7b6cf2f6ff04">easybuild-2.1.1.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/7d/9f/adf042ba10deba17c8ec797a3aca59945b08a8dcd0295940ff524cbf6985/easybuild-2.2.0.tar.gz#sha256=199fb04fcf1e61c97ec9f06f62bfcd1506169c5a0326b388ab0d2abc504f3770">easybuild-2.2.0.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/a9/04/c2107029c150cdc8b714522dfd47ac5cdc19b7be713205cb12e31c42d216/easybuild-2.3.0.tar.gz#sha256=70489d6f98bd48b95b47b4152073e452e9036bbe4c69af523af9fa32ed32b71b">easybuild-2.3.0.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/f4/e0/568a7d19bb755df3f59b903edbacb8b9a40c240d545a5c616dddfeb19687/easybuild-2.4.0.tar.gz#sha256=55e53a7913c1389cf2585da5becf3ea8ede651490176cfb57e6483f93d8c2002">easybuild-2.4.0.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/78/59/f848c1141421a072e40c31a666585c6cb3d089c37e1a40d26c8b005c84c8/easybuild-2.5.0.tar.gz#sha256=02077fee9ea3ded8e1fad8736ce538fbc123641ef2a4ac89877b071a5ed6b877">easybuild-2.5.0.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/69/f7/26cae104723a747a2176a4b6743e38ebac519964141af76e75be16cf55de/easybuild-2.6.0.tar.gz#sha256=8b346a8f81fac81c76e599b35ee77a25771cec95d61d78ecb81f5a9f2d59a8d0">easybuild-2.6.0.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/5b/03/e135b19fadeb9b1ccb45eac9f60ca2dc3afe72d099f6bd84e03cb131f9bf/easybuild-2.7.0.tar.gz#sha256=ff01d2758ebbe387aaab199c6f13195c1c933ac41181dd446ac21287bcade584">easybuild-2.7.0.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/f4/73/42494b726f6fad1fe41346e93d6af261ac3ad8b227f50466b71477fd1b2d/easybuild-2.8.0.tar.gz#sha256=c9e1ef2b3d2bb1abd1d69563467272c82245891f2fe2a8d944f9e14e382180b4">easybuild-2.8.0.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/89/8f/40d8606cc8baaa71a9aa9041f83283b511faf247846f804817a436ee55da/easybuild-2.8.1.tar.gz#sha256=bd4b02a7b9c497e955895716f1bc3590ada940f9f6073958c7da829dca9cfb3a">easybuild-2.8.1.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/60/dd/9441f33ee94d926e391c5c71c9f51f073cad8871e0a12a3fa1584179dd08/easybuild-2.8.2.tar.gz#sha256=cfc94feb6ec63ccb2885a859d1c6b5bdbef1ec5e46d3bafb26c23ebf95630712">easybuild-2.8.2.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/d5/74/9e0d4d9aabe86c0e06b2fa97ddb4c875dd41b2eabcb16cfe05dd146f4369/easybuild-2.9.0.tar.gz#sha256=586e448d416ad8dd86d944e64a2c9570bf38d8842ac64af4266445a691bd9151">easybuild-2.9.0.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/d3/65/0f5ef53f9ee9c0ed6933ebb8594b52eb3a07a45dba6951c6e88a5a2448a4/easybuild-3.0.0.tar.gz#sha256=e96e8d17efec913691168ae8cc2752e12f7e2ce1dec6ae9189ffcf89a6d8bd94">easybuild-3.0.0.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/91/bd/1147b0f31f23592fffd1edfd4ebdeaaa51533e3331f20301293cc334b237/easybuild-3.0.1.tar.gz#sha256=6f1aadcf913bfd71b3ba6e130ac10b56d7367a65a22b0d2651fa433b603445aa">easybuild-3.0.1.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/1f/72/1eef2de2dddf26c7abd852ef2916b84f97f13a67ea2039ac1d19bf2e859c/easybuild-3.0.2.tar.gz#sha256=5a862b232010c67a61f639d34c78a176df316ea8e98351e3dd52539a571ab2c1">easybuild-3.0.2.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/b8/31/8d8582b0531533204b33f8d0f2be92e28e89eee3f7db1995dcb84e854bea/easybuild-3.1.0.tar.gz#sha256=d23c1218fed2e14bf3c7c713e9f491514e301c3af9ef3e7d34e00e3115a17b80">easybuild-3.1.0.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/a3/d7/1ff08874fe08e34aaf278c1152c3316f08a7a705221d06845151ac73097a/easybuild-3.1.1.tar.gz#sha256=2fc7b5a6e4732992b258193068d3693a5304efa1902ef08e57e4653d5b66137b">easybuild-3.1.1.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/7b/74/4132806b35cb6308a8776297cfa7fec5c8cfa3bc94a8701d209ed3fdd18e/easybuild-3.1.2.tar.gz#sha256=a966a08e41d3557d7fd3dc5322180c006d27281d9ecc1b1fce1b4518c32664d4">easybuild-3.1.2.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/20/85/995af85a66100d010841be7a4eed9ab98d7187cd8ad9cc627e7eaa7b2800/easybuild-3.2.0.tar.gz#sha256=2e565841fc6740b3dff524773fd09254ca6a374506bf66263210175f3c13f790">easybuild-3.2.0.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/08/76/9b729dfe2a51d42b085f97bb85f65f030578537c41640a9172ec0fb1a5aa/easybuild-3.2.1.tar.gz#sha256=e980ff22e1ccfee04151d5d5d78a377045fa383ed89a0446f2b47d5718c60ee4">easybuild-3.2.1.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/74/38/2cbcea9c01cdb773d6d66db8295d7228945abbb881e68f75b90e701d4afb/easybuild-3.3.0.tar.gz#sha256=2c05a39b7278b58a7e2e7c300ece843289af84c5f4d08c61fbdf498fc14d0b41">easybuild-3.3.0.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/da/9e/c9017f93453f9a9c6d343dbe5a489f88a31ca67576721ab1a59f6083cc7a/easybuild-3.3.1.tar.gz#sha256=f0df9d33c4ef910ca3cf6c8a08e92e508b9836a1d3c58d0181d3f2411fa50723">easybuild-3.3.1.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/93/41/574d01f352671fbc8589a436167e15a7f3e27ac0aa635d208eb29ee8fd4e/easybuild-3.4.0.tar.gz#sha256=d870b27211f2224aab89bfd3279834ffb89ff00ad849a0dc2bf5cc1691efa9d2">easybuild-3.4.0.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/1f/26/440f36fa41c37ffd55fcb8f5f2c18917361e72f9d65e0382cd36ba4943c1/easybuild-3.4.1.tar.gz#sha256=89178a71e405a6cd9ba9d94579ef2516d590fafabfe2c4016e1bab064b9fd113">easybuild-3.4.1.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/5e/f3/09a84566524f6795afd5f94e4494b6689d28e8155b40912159e63f55f990/easybuild-3.5.0.tar.gz#sha256=2c939052b8de4bd932a45d8c9aedf703fd31268a05063e89b0c828bbddca8431">easybuild-3.5.0.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/c3/0b/33a3e710ebb809e5b9e3289b4b84018e1209a948e39bb80d53fa79e6ce54/easybuild-3.5.1.tar.gz#sha256=7956bc2e0f18f8b41bb83b4e02f91edf542c900503f59364f98fcfcc0cd13439">easybuild-3.5.1.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/3c/2b/f08d51398657c4c67f4f1b341f2acaca210a37d1de18ef1a3e3076187608/easybuild-3.5.2.tar.gz#sha256=cac073d2d39b7605497ef08bb64c2bab6101012a15b74d23e40a9fef33f87538">easybuild-3.5.2.tar.gz</a><br>
    <a href="https://files.pythonhosted.org/packages/ae/03/930c66b7076688c44ca02acfae4876b8c17fb61a057f01d8ec25f1ed3ca0/easybuild-3.5.3.tar.gz#sha256=477ec25142674c9c654debd40f3ee7a783ae1141b89e339b7243c25eeaa54037">easybuild-3.5.3.tar.gz</a><br>
    </body>
</html>
```

**Comment by jamadden** [comment] 2018-03-16 15:56
I cannot reproduce this. Perhaps the CDN cached a few pages in the process of being updated?

**Comment by di** [comment] 2018-03-16 15:59
This is due to https://status.python.org/incidents/btjtz01lzp88, you were getting `/simple` from https://github.com/pypa/warehouse/

I also don't see what the problem is, the HTML validates fine: https://validator.w3.org/nu/?doc=https%3A%2F%2Fpypi.org%2Fsimple%2Feasybuild%2F

Maybe it's the indentation of the `</body>` tag?

**Comment by vanzod** [comment] 2018-03-16 16:00
I confirm the same error @boegel reported.

```
$ curl -L https://pypi.org/simple/easybuild > easybuild.html
$ python -c "from xml.etree import ElementTree; ElementTree.parse('easybuild.html')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: mismatched tag: line 65, column 6
```

**Comment by boegel** [comment] 2018-03-16 16:03
@di Can't seem to get passed the parse error, even after playing with the indentation of `</body>` (same as `<body>` line or no indent both didn't fix the parse error).

**Comment by boegel** [comment] 2018-03-16 16:04
@di Since this is actually a problem with warehouse, should I report it there?

**Comment by di** [comment] 2018-03-16 16:04
Looks like it's the `<br>` tags not being `<br/>`. Fixing...

**Comment by di** [comment] 2018-03-16 16:05
@boegel Nope this is fine!

**Comment by boegel** [comment] 2018-03-16 16:07
For reference, here's what `https://pypi.python.org/simple/easybuild` used to serve (hat tip @zao): https://gist.github.com/zao/c9c6055dce00b57c7933ae3e4c8e0754 . This parses fine with `ElementTree.parse`.

**Comment by boegel** [comment] 2018-03-16 16:09
@di Changing `<br>` to `<br/>` indeed fixes the parse issue for me, and legacy PyPI was indeed serving a page with `<br/>` rather than `<br>`.

**Comment by di** [comment] 2018-03-16 16:22
Fixed in https://github.com/pypa/warehouse/pull/3294.

**Comment by di** [comment] 2018-03-16 16:22
Thanks for the report @boegel!

**Closed by di** 2018-03-16 16:22 UTC

**Comment by boegel** [comment] 2018-03-16 16:36
@di No problem! :shipit: 

Just to be clear: is this actually live on warehouse already, or is the (temporary?) redirect from legacy to warehouse no longer active now?

**Comment by di** [comment] 2018-03-16 16:56
Both:

* the fix is live on warehouse, so if you want to point whatever you're using at `pypi.org/simple` instead it should work.
* the load test is finished for now, so `pypi.python.org/simple` is currently serving the original, working `/simple`.
