### ISSUE TITLE
searching for "salt" returns "Something went wrong"

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#469] opened 2016-06-16 18:38 UTC
Originally reported by: **Denys Duchier (Bitbucket: [denys_duchier](https://bitbucket.org/denys_duchier), GitHub: Unknown)**

----------------------------------------

searching for other things seems to work though!

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/469

**Comment by berkerpeksag** [comment] 2016-06-19 18:59
This is a duplicate of #424.

**Closed by berkerpeksag** 2016-06-19 18:59 UTC
