### ISSUE TITLE
Request new / changed trove classifiers for Zope

### ISSUE THREAD

**Issue by loechel** [pypa/pypi-legacy#709] opened 2017-09-28 15:52 UTC
Hi I am a Zope/Plone core maintainer and Plone Foundation Board of Directors member.
Due to the Update Process of Plone and therefore Zope to Python 3, we renamed Zope2 back to Zope and add a new Major Version.

Would it be possible to get the following PyPI trove classifieres:

Framework :: Zope
Framework :: Zope :: 2
Framework :: Zope :: 3
Framework :: Zope :: 4

and if possible deprecate the old classifiers:

Framework :: Zope2
Framework :: Zope3

Thanks

**Comment by ewdurbin** [comment] 2017-09-29 02:14
@loechel unfortunately we don't have a process for deprecating classifiers. adding a classifier is a straight forward task, but modifying or renaming classifiers is not currently supported.

the primary issues with renaming classifiers (generally):
  - is there a 1-to-1 map between old and new classifiers?
  - are the semantic meanings the same?
  - what happens to new uploads which use a deprecated classifier? are they automatically remapped or rejected?

if we go the route of renaming or deprecating classifiers, that will need to be implemented in https://github.com/pypa/warehouse as it is not a bug in this codebase.

so I present two options:
  - option a) add all of the new classifiers, leaving the old classifiers in place until such a time that renaming or deprecating classifiers is supported
  - option b) file an issue on https://github.com/pypa/warehouse/issues for supporting classifier renaming and wait for that to be resolved

**Comment by icemac** [comment] 2017-09-29 06:13
I'd vote for option a). Meanwhile we can hope that other classifiers need deprecation in the future so this will be eventually fixed in warehouse.

**Comment by loechel** [comment] 2017-09-29 07:06
@ewdurbin I follow @icemac (one of the release managers of Zope Core Packages) that we should go with option a) for now.

As we also have a few things, we need in warehouse, I might be able to make a pull request for option b) at the Plone Conf sprint or later. 

As we do have a 1-to-1 mapping here:
 
    Framework :: Zope2 --> Framework :: Zope :: 2
    Framework :: Zope3 --> Framework :: Zope :: 3

that could be a good test case if that works.

Thanks for your help.

**Comment by ewdurbin** [comment] 2017-09-29 12:35
The following Classifiers were created:

- `Framework :: Zope`
- `Framework :: Zope :: 2`
- `Framework :: Zope :: 3`
- `Framework :: Zope :: 4`

**Comment by ewdurbin** [comment] 2017-09-29 12:35
to follow up, please file an issue with https://github.com/pypa/warehouse/issues regarding classifier deprecation/mapping.

**Closed by ewdurbin** 2017-09-29 12:35 UTC
Labels: classifier-request
