### ISSUE TITLE
IntelHex package links to malware

### ISSUE THREAD

**Issue by jpwright** [pypa/pypi-legacy#694] opened 2017-08-29 17:33 UTC
https://pypi.python.org/pypi/IntelHex/1.2

The "Home Page" link directs to a compromised website serving malware.

**Comment by jamadden** [comment] 2017-08-29 19:06
I agree that the "Home Page" links seem suspicious, though I didn't try to verify if they were malware, adware, or just annoying (I followed them through several redirects manually on the command line) :) 

Fortunately, the current version of IntelHex is 2.1, and the "plain" URL goes there: https://pypi.python.org/pypi/IntelHex/. It features a home page that just [points to github](https://github.com/bialix/intelhex/). Version 1.5, from 2015, is the first version that's actually hosted on PyPI and links to launchpad for its home page (1.3 and 1.4 still link to the suspicious site). So hopefully not many people will encounter this.

Have you tried opening an issue at the current github [home page](https://github.com/bialix/intelhex/issues) asking for the compromised versions to be removed? Since they do not actually contain any hosted files, and pip no longer tries to follow external links, there should be very minimal impact by doing so. That may be the speediest way to get this resolved.

**Comment by bialix** [comment] 2017-08-30 11:20
@jpwright Thank you for info, I will remove those older releases. That was my old home page which is not my page for many years now.

**Comment by jamadden** [comment] 2017-08-30 11:27
@bialix Thank you! I confirmed that the compromised releases have been removed, so I'll go ahead and close this.

@jpwright Thanks for the report!

**Comment by bialix** [comment] 2017-08-30 11:27
I've just removed all releases past 1.5. But I keep 1.5 release for now, because I don't see any links to my old home page. If there any problems with 1.5 just letting me know.

**Closed by jamadden** 2017-08-30 11:27 UTC
