### ISSUE TITLE
"Something went wrong" when searching for pyqt5

### ISSUE THREAD

**Issue by titusjan** [pypa/pypi-legacy#475] opened 2016-06-28 13:42 UTC
When searching for the pyqt5 package I get the message that "Something went wrong".
https://pypi.python.org/pypi?%3Aaction=search&term=pyqt5&submit=search

Probably related: searching with pip gives the following error:
```
$> pip-3.5 search pyqt5
Exception:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pip/commands/search.py", line 43, in run
    pypi_hits = self.search(query, options)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pip/commands/search.py", line 60, in search
    hits = pypi.search({'name': query, 'summary': query}, 'or')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/xmlrpc/client.py", line 1092, in __call__
    return self.__send(self.__name, args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/xmlrpc/client.py", line 1432, in __request
    verbose=self.__verbose
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pip/download.py", line 767, in request
    return self.parse_response(response.raw)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/xmlrpc/client.py", line 1322, in parse_response
    return u.close()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/xmlrpc/client.py", line 655, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 1: "<type 'exceptions.KeyError'>:'_pypi_hidden'">

```

**Comment by berkerpeksag** [comment] 2016-06-28 13:47
Thanks for the report. I believe this is a duplicate of #421.

**Closed by berkerpeksag** 2016-06-28 13:47 UTC

**Comment by titusjan** [comment] 2016-06-28 14:08
Indeed it is a duplicate. Thanks.

There seem to be quite some packages affected by it (I just had the same issue with the 'distribute' package). Any news about a fix?
