### ISSUE TITLE
Searching by keywords stopped working.

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#325] opened 2015-08-25 20:45 UTC
Originally reported by: **Alessandro Molina (Bitbucket: [_amol_](https://bitbucket.org/_amol_), GitHub: Unknown)**

----------------------------------------

Just noticed that searching for keywords doesn't lead to any result anymore. This broke the TurboGears2 cogbin on website, which now appears empty: http://turbogears.org/cogbin.html

Search for **turbogears2.extension** leads to an empty result ( https://pypi.python.org/pypi?%3Aaction=search&term=turbogears2.extension&submit=search ).

Even though it's known that there are packages with that keywrod (See https://pypi.python.org/pypi/tgext.pluggable/0.5.4 for example) it returns no results.

This happens when called from xmlrpc too:

```
#!python

import xmlrpclib
client = xmlrpclib.ServerProxy("https://pypi.python.org/pypi/")
print client.search({'keywords': 'turbogears2.extension'})
```

It worked until recently, and it seems to only have issues with keywords that contain a dot.

https://pypi.python.org/pypi?%3Aaction=search&term=turbogears2&submit=search works and also lists packages containing keywords, while https://pypi.python.org/pypi?%3Aaction=search&term=turbogears2.application&submit=search and https://pypi.python.org/pypi?%3Aaction=search&term=turbogears2.extension&submit=search do not.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/325

**Comment by kernc** [comment] 2016-06-18 15:15
Duplicate of https://github.com/pypa/pypi-legacy/issues/397

**Closed** 2016-06-18 15:16 UTC
Labels: bug, duplicate, major
