### ISSUE TITLE
Error during upload of documentation

### ISSUE THREAD

**Issue by lionel-martin** [pypa/pypi-legacy#473] opened 2016-06-21 07:39 UTC
I got a 403 error when I uploaded an archive containing the documentation for our project on PyPI. The attachment give the exact error.

I uploaded, as requested, a zip containing a file "index.html" at the root and different folders around.

![screenshot from 2016-06-20 13-03-53](https://cloud.githubusercontent.com/assets/4763322/16221601/0930fc3e-3794-11e6-88d3-d23cb53b6af0.png)

**Comment by ewdurbin** [comment] 2016-07-08 13:05
What size was the zip file you were attempting to upload? Unfortunately we have to have some relatively aggressive timeouts that may have caused this issue.

**Comment by lionel-martin** [comment] 2016-07-08 14:01
4.3Mo

**Comment by ewdurbin** [comment] 2016-07-13 14:19
requests taking longer than 60s timeout unfortunately. i've been doing some maintenance around our backends as well as some performance improvements that should alleviate backend bottlenecks caused by congestion.

@lionel-martin please try uploading again and let me know if this is still a problem. at that point i'm afraid it may be that you need a slightly faster internet connection to successfully upload the package documentation before it times out.

**Comment by lionel-martin** [comment] 2016-07-14 11:46
The problem is still there.
I'm using a 40Mbps upload link so I don't think that this is due to the internet connection.

I kept testing a few things. I tried to upload a zip containing only the index.html file. Here is the answer in the browser :
```Error processing form```
```Error: Another doc upload is in progress.```

Finally I noticed that even though I get the 403 error. Once the upload and unzip are completed. The doc is correctly displayed on the pythonhosted.org website.

Hope this might help you.

**Comment by ewdurbin** [comment] 2016-07-14 12:29
@lionel-martin it sounds like the error you've indicated is within reality. what are you using to upload this documentation? based on the error and behavior it _does_ sound like you have multiple uploads occurring simultaneously somehow. i'm unable to reproduce (similarly with a zip file containing only an index.html)

any more details or steps to reproduce would be beneficial here.

**Comment by lionel-martin** [comment] 2016-07-14 13:14
Ok here are the full details:

1) I tried to upload my full doc in a zip from the release page of my package, containing a file index.html at the root level.
2) When I click on "Upload Documentation", my browser try to load a new page, spins for some time "Connecting..." (quite long, probably the 60sec you mentioned before)
3) After the 60sec, I obtain always a "403" error as described above.
4) If I check the webpage on pythonhosted during this time, it's a 404 error.
5) If I check the webpage on pythonhosted after a reasonable amount of time (for a single file, waiting slightly more than the minute of loading is enough), I get the correct content.
6) While in state 4, if I try to upload another documentation, I don't have to wait the 60sec and directly get the "another doc upload is in progress" error

Technical details : FF 47.0, Ubuntu 16.4.

**Comment by di** [comment] 2018-04-04 04:27
Closing, we don't support uploading documentation anymore.

**Closed by di** 2018-04-04 04:27 UTC
