### ISSUE TITLE
package cannot be installed by pip command.

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#404] opened 2016-02-26 01:37 UTC
Originally reported by: **지환 김 (Bitbucket: [johnnykim](https://bitbucket.org/johnnykim), GitHub: [johnnykim](https://github.com/johnnykim))**

----------------------------------------

I made 'django-slack-notifications' package, it can be installed by pip when I first created.

However, after I removed the project completely and re-registered it, I cannot install from pip command in my terminal.

So, I made 'django-slack-notification' package (not notification's' but notifiacition), it can be installed by pip command.

What's wrong with my project?

I uploaded it two days ago.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/404

**Comment by berkerpeksag** [comment] 2016-07-11 04:40
Because there is no sdist or wheel file associated with the 1.0.0 release: https://pypi.python.org/pypi/django-slack-notifications

My guess is your upload was somehow failed (most likely due to a transient failure) but a new release was created anyway. It looks like a duplicate of https://github.com/pypa/pypi-legacy/issues/253 to me.

**Closed by berkerpeksag** 2016-07-11 04:40 UTC
