### ISSUE TITLE
Problems searching package 'SH'

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#426] opened 2016-03-26 12:55 UTC
Originally reported by: **Pedro Pezzarini (Bitbucket: [PedroPezzarini](https://bitbucket.org/PedroPezzarini), GitHub: Unknown)**

----------------------------------------

Hi! i have an error page in pypi, when i was trying searching info about the 'sh' package.
Regards
Peter

![Captura de pantalla 2016-03-26 a las 9.49.56 a.m..png](https://bitbucket.org/repo/j9KaaX/images/2572871394-Captura%20de%20pantalla%202016-03-26%20a%20las%209.49.56%20a.m..png)

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/426

**Comment by berkerpeksag** [comment] 2016-06-19 18:57
As timokasse stated, this is a duplicate of #424.

**Closed by berkerpeksag** 2016-06-19 18:57 UTC
