### ISSUE TITLE
Package 'ldtp' is broken

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#414] opened 2016-03-11 11:35 UTC
Originally reported by: **mwicat (Bitbucket: [mwicat](https://bitbucket.org/mwicat), GitHub: [mwicat](https://github.com/mwicat))**

----------------------------------------

The package claims to be in version 3.5.0:
https://pypi.python.org/pypi/ldtp/3.5.0

But on https://pypi.python.org/simple/ldtp/ there is only version 1.0.0. The same for https://pypi.python.org/pypi/ldtp/json

Pip also thinks there is only 1.0.0, this would be ok but even this version results in error on install:

```
$ sudo pip install ldtp --verbose
Collecting ldtp
  1 location(s) to search for versions of ldtp:
  * https://pypi.python.org/simple/ldtp/
  Getting page https://pypi.python.org/simple/ldtp/
  Looking up "https://pypi.python.org/simple/ldtp/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.python.org
  "GET /simple/ldtp/ HTTP/1.1" 200 201
  Updating cache with response from "https://pypi.python.org/simple/ldtp/"
  Caching b/c date exists and max-age > 0
  Analyzing links from page https://pypi.python.org/simple/ldtp/
    Found link https://pypi.python.org/packages/source/l/ldtp/ldtp-1.0.0.tar.gz#md5=b3fc52b1ab2c48b825bcc463003d95f9 (from https://pypi.python.org/simple/ldtp/), version: 1.0.0
  Using version 1.0.0 (newest of versions: 1.0.0)
  Looking up "https://pypi.python.org/packages/source/l/ldtp/ldtp-1.0.0.tar.gz" in the cache
  No cache entry available
  "GET /packages/source/l/ldtp/ldtp-1.0.0.tar.gz HTTP/1.1" 200 615135
  Downloading ldtp-1.0.0.tar.gz (615kB)
  Downloading from URL https://pypi.python.org/packages/source/l/ldtp/ldtp-1.0.0.tar.gz#md5=b3fc52b1ab2c48b825bcc463003d95f9 (from https://pypi.python.org/simple/ldtp/)
    99% |████████████████████████████████| 614kB 58.6MB/s eta 0:00:01  Updating cache with response from "https://pypi.python.org/packages/source/l/ldtp/ldtp-1.0.0.tar.gz"
  Caching due to etag
    100% |████████████████████████████████| 624kB 2.8MB/s 
  Running setup.py (path:/tmp/pip-build-QjNon1/ldtp/setup.py) egg_info for package ldtp
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-QjNon1/ldtp/setup.py'
Cleaning up...
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-QjNon1/ldtp/
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 299, in run
    requirement_set.prepare_files(finder)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 591, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 127, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 430, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 718, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-QjNon1/ldtp/
Starting new HTTPS connection (1): pypi.python.org
"GET /pypi/pip/json HTTP/1.1" 200 57486
```

Download url http://download.freedesktop.org/ldtp/3.x/3.5.x/ldtp-3.5.0.tar.gz does not work as well.

Seems that everything about this package is broken. On debian you have to do apt-get install ldtp but this solution does not play nicely with virtualenv.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/414

**Comment by berkerpeksag** [comment] 2016-06-21 02:47
This is basically a duplicate of #365. The broken URL should be reported to LDTP developers: https://wiki.freedesktop.org/ldtp/Mailing_List_IRC/

**Closed by berkerpeksag** 2016-06-21 02:47 UTC
