### ISSUE TITLE
PyPi index does not remove deleted entries

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#375] opened 2016-01-15 00:51 UTC
Originally reported by: **Ben Jolitz (Bitbucket: [benjolitz](https://bitbucket.org/benjolitz), GitHub: [benjolitz](https://github.com/benjolitz))**

----------------------------------------

We deleted several packages that shouldn't have been added but they still show up on a 'pip search'.

How long can we expect those entries to remain? We made our deletes several days ago.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/375

**Comment by berkerpeksag** [comment] 2016-07-07 05:03
This is a duplicate of #352.

**Closed by berkerpeksag** 2016-07-07 05:03 UTC
