### ISSUE TITLE
Cannot delete or modify documentation for http://pypi.python.org/pypi/slash

### ISSUE THREAD

**Issue by vmalloc** [pypa/pypi-legacy#489] opened 2016-07-26 12:19 UTC
Tried re-uploading documentation, both via direct `upload_docs` and also via specifying `--upload-dir` explicitly. Unfortunately it seems that the docs on http://pythonhosted.org/slash remain unchanged, and are stuck in time.

I also can't seem to change the documentation URL in the package details, so my users are stuck being directed to an obsolete documentation...

How can I update the docs or alternatively just direct the link at http://slash.readthedocs.org ?

Thanks in advance

**Comment by vmalloc** [comment] 2016-07-28 10:52
I worked around it for now by using sphinx-pypi-upload and the `upload_sphinx` command...

**Comment by berkerpeksag** [comment] 2016-10-04 17:57
Thanks for the report. This is a duplicate of #24.

**Closed by berkerpeksag** 2016-10-04 17:57 UTC
