### ISSUE TITLE
Failing to upload package

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#419] opened 2016-03-18 10:43 UTC
Originally reported by: **Daniele Varrazzo (Bitbucket: [dvarrazzo](https://bitbucket.org/dvarrazzo), GitHub: [dvarrazzo](https://github.com/dvarrazzo))**

---

Hello,

I'm trying to upload the package `ltree` on PyPI. First I created the package with version `0.0.0`, then wrote some code, the `setup.py` and tried `register` and `sdist upload`. The client reports no error but the package doesn't show up in PyPI.

The `register` run:

```
piro@risotto:~/src/py-ltree$ python setup.py register
running register
running egg_info
writing ltree.egg-info/PKG-INFO
writing top-level names to ltree.egg-info/top_level.txt
writing dependency_links to ltree.egg-info/dependency_links.txt
reading manifest file 'ltree.egg-info/SOURCES.txt'
writing manifest file 'ltree.egg-info/SOURCES.txt'
running check
Registering ltree to http://www.python.org/pypi
Server response (200): OK
```

The `upload` run:

```
piro@risotto:~/src/py-ltree$ python setup.py sdist upload
running sdist
running egg_info
writing ltree.egg-info/PKG-INFO
writing top-level names to ltree.egg-info/top_level.txt
writing dependency_links to ltree.egg-info/dependency_links.txt
reading manifest file 'ltree.egg-info/SOURCES.txt'
writing manifest file 'ltree.egg-info/SOURCES.txt'
running check
creating ltree-0.0.2
creating ltree-0.0.2/ltree
creating ltree-0.0.2/ltree.egg-info
making hard links in ltree-0.0.2...
hard linking README.rst -> ltree-0.0.2
hard linking setup.py -> ltree-0.0.2
hard linking ltree/__init__.py -> ltree-0.0.2/ltree
hard linking ltree.egg-info/PKG-INFO -> ltree-0.0.2/ltree.egg-info
hard linking ltree.egg-info/SOURCES.txt -> ltree-0.0.2/ltree.egg-info
hard linking ltree.egg-info/dependency_links.txt -> ltree-0.0.2/ltree.egg-info
hard linking ltree.egg-info/top_level.txt -> ltree-0.0.2/ltree.egg-info
Writing ltree-0.0.2/setup.cfg
Creating tar archive
removing 'ltree-0.0.2' (and everything under it)
running upload
Submitting dist/ltree-0.0.2.tar.gz to http://www.python.org/pypi
Server response (200): OK
```

The metadata got a package version `0.0.1`, which I think was created in some previous upload attempt. The classifiers are stuck to what I submitted in `0.0.0` though. No sdist package has been uploaded ad `pip install ltree` doesn't find anything.

This is the [setup.py](https://github.com/dvarrazzo/py-ltree/blob/a35e39d59a681d46ddec4f5d83ba453ae793d017/setup.py) at the state in which I've tried the last upload. My last upload attempt was around Fri Mar 18 10:42:03 GMT 2016.

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/419

**Comment by berkerpeksag** [comment] 2017-07-09 09:53
I just tried to upload a35e39d59a681d46ddec4f5d83ba453ae793d017 of [py-ltree](https://github.com/dvarrazzo/py-ltree) to TestPyPI as "ltree-test" and it worked. You can see the uploaded file at https://test.pypi.org/project/ltree-test/#files and try to install it by using the following command:

```sh
$ pip install -i https://test.pypi.org/simple ltree-test
Collecting ltree-test
  Downloading https://test-files.pythonhosted.org/packages/e2/64/b85c818b730a67646dd0dcd109ed251439d76507623eae0dde60566f5494/ltree-test-0.0.3.tar.gz
Installing collected packages: ltree-test
  Running setup.py install for ltree-test ... done
Successfully installed ltree-test-0.0.3
```

Your problem might be caused by a transient error on legacy PyPI. Could you try again with using pypi.org? You might find https://packaging.python.org/guides/migrating-to-pypi-org/ helpful for migrating from legacy PyPI to pypi.org.

Also, this looks like a duplicate of #282.

**Comment by di** [comment] 2018-04-04 04:35
Closing due to inactivity.

**Closed by di** 2018-04-04 04:35 UTC
