### ISSUE TITLE
no links on https://pypi.python.org/simple/pywin32/

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#388] opened 2016-02-05 20:12 UTC
Originally reported by: **Rob Boer (Bitbucket: [dutchrob](https://bitbucket.org/dutchrob), GitHub: [dutchrob](https://github.com/dutchrob))**

----------------------------------------

Pip install pywin32 did not work for me and appears to be because
https://pypi.python.org/simple/pywin32/ 
includes no links

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/388

**Comment by berkerpeksag** [comment] 2016-06-21 02:53
This is a duplicate of #365.

**Closed by berkerpeksag** 2016-06-21 02:53 UTC
