### ISSUE TITLE
unable to upload documentation

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#334] opened 2015-09-03 15:15 UTC
Originally reported by: **cmorisset (Bitbucket: [cmorisset](https://bitbucket.org/cmorisset), GitHub: [cmorisset](https://github.com/cmorisset))**

----------------------------------------

Hi,

I'm trying to upload documentation at http://pythonhosted.org/PyNeb using the same kind of  .zip file as always, but systematicaly failed (with Error 503 backend read error). I tried from different IPs and locations, no way.
Thanks for any tip or info.
Cheers,
Christophe

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/334

**Comment by berkerpeksag** [comment] 2016-06-21 03:10
This is a duplicate of #266.

**Closed by berkerpeksag** 2016-06-21 03:10 UTC
