### ISSUE TITLE
Search and downloads stats doesn't work for the "uvloop" package

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#451] opened 2016-05-07 22:55 UTC
Originally reported by: **1st1 (Bitbucket: [1st1](https://bitbucket.org/1st1), GitHub: [1st1](https://github.com/1st1))**

----------------------------------------

1. The search only shows up an old version of uvloop (the archive was manually deleted), which brings the user to a 404 page.

2. The downloads statistics doesn't look right. It seems that the stats are for that old version that shows up in search results.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/451

**Comment by kernc** [comment] 2016-06-18 15:16
Duplicate of https://github.com/pypa/pypi-legacy/issues/397

**Closed** 2016-06-18 15:17 UTC
Labels: bug, duplicate, minor
